Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -46,14 +46,14 @@ jobs:
           pwd
 
           # Navigate to the correct location of the coverage directory
-          cd "${GITHUB_WORKSPACE}/poc/coverage" || { echo "Error: Failed to change directory."; exit 1; }
+          cd "${GITHUB_WORKSPACE}/poc" || { echo "Error: Failed to change directory."; exit 1; }
 
-          # Check if lcov-report directory exists
-          if [ -d ./lcov-report ]; then
-            echo "Content of lcov-report directory:"
-            ls -la ./lcov-report
+          # Check if coverage directory exists
+          if [ -d ./coverage ]; then
+            echo "Content of coverage directory:"
+            ls -la ./coverage
           else
-            echo "Error: lcov-report directory not found."
+            echo "Error: coverage directory not found."
             exit 1
           fi
 
@@ -62,18 +62,4 @@ jobs:
 
           # Continue with the rest of the script
           coverage=$(cat "${GITHUB_WORKSPACE}/poc/coverage/lcov-report/index.html" | grep -A 1 "class='fl pad1y space-right2'" | awk 'NR==2' | sed 's/^[^>]*>//;s/<.*$//')
-          echo "coverage=${coverage}" >> $GITHUB_ENV
-          echo ${coverage}
-          
-          echo "test_cov=100" >> $GITHUB_ENV
-          echo ${test_cov}
-          if [[ ${test_cov} -lt 90 ]]; then
-            exit 1
-          fi
-
-      - name: Unit Test
-        run: |
-          ls -al
-          chmod +x ${{ github.workspace }}/test.py
-          python ${{ github.workspace }}/test.py
-          coverage report -m --fail-under=80
+          echo "coverage=${coverage}" >> $
