Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -45,8 +45,8 @@ jobs:
           echo "Current working directory before cd:"
           pwd
 
-          # Navigate to the coverage directory
-          cd ./coverage || { echo "Error: Failed to change directory."; exit 1; }
+          # Navigate to the correct location of the coverage directory
+          cd "${GITHUB_WORKSPACE}/coverage" || { echo "Error: Failed to change directory."; exit 1; }
 
           # Check if lcov-report directory exists
           if [ -d ./lcov-report ]; then
@@ -60,20 +60,4 @@ jobs:
           # Navigate back to the original directory
           cd - || { echo "Error: Failed to change back to the original directory."; exit 1; }
 
-          # Continue with the rest of the script
-          coverage=$(cat ./coverage/lcov-report/index.html | grep -A 1 "class='fl pad1y space-right2'" | awk 'NR==2' | sed 's/^[^>]*>//;s/<.*$//')
-          echo "coverage=${coverage}" >> $GITHUB_ENV
-          echo ${coverage}
-          
-          echo "test_cov=100" >> $GITHUB_ENV
-          echo ${test_cov}
-          if [[ ${test_cov} -lt 90 ]]; then
-            exit 1
-          fi
-
-      - name: Unit Test
-        run: |
-          ls -al
-          chmod +x ${{ github.workspace }}/test.py
-          python ${{ github.workspace }}/test.py
-          coverage report -m --fail-under=80
+          # Continue with t
